### ISSUE TITLE
`bzsanity` needs to be calculated

### ISSUE THREAD

**Issue by KayLeung** [kyl191/bzdownloader#1]
https://github.com/kyl191/bzdownloader/blob/c9451c41886850872d7b5d161e90fb474905eaae/bzdownloader/bzdownloader.py#L372

This is a unique value per client. I've done a quick test and confirmed it works. @see below:
https://reverseengineering.stackexchange.com/questions/12193/backblaze-16-bit-checksum-bzsanity

**Comment by kyl191** [comment]
Well that explains what the value it, thanks for the links. :)
